{
    "planId":"GY3xP3AceuG04eCP9rj",
    "areaIds":[
        "dWDV5AKnCqmXKQh5u8H"
    ],
    "timePrice":[
        {
            "start":"08:00:00",
            "end":"22:00:00",
            "price":"40.0"
        }
    ],
    "venueId":"u5T6DN13PfJmUsXHkkP",
    "dates":[
        "2017-09-01",
        "2017-11-01"
    ],
    "type":"custom",
    "planName":"方案1"
}

{
    "venueId":"JfQ0YK0rzpBuPp4q21z",
    "dates":[

    ],
    "planName":"ggg",
    "timePrice":[
        {
            "start":"13:00:00",
            "end":"15:00:00",
            "price":"20.1"
        }
    ],
    "type":"weekday",
    "areaIds":[
        "CkfCKPdG9LwH2G5zfdN","DuMtjpcGUxxgGCbfQM2"
    ]
}

{
    "planId":"hdPn94DO0hEelUaw5Ca",
    "venueId":"1",
    "planName":"正常",
    "areaIds":[
        "BSUtfoR1HZdWBsWFmgT","rPaFuDyevBE0te7HxLb"
    ],
    "type":"weekday",
    "timePrice":[
         {
            "start":"09:00:00",
            "end":"23:00:00",
            "price":"58"
        }
    ]
}
